// Mock products data
export const mockProducts = [
  {
    id: 1,
    name: 'Áo thun nam cổ tròn basic',
    slug: 'ao-thun-nam-co-tron-basic',
    price: 199000,
    discountPrice: 149000,
    discount: 25,
    description: 'Áo thun nam cổ tròn basic chất liệu cotton 100%, thoáng mát, co giãn tốt. Phù hợp cho mọi hoạt động hàng ngày.',
    categoryId: 1,
    categorySlug: 'ao-thun',
    category: 'Áo thun',
    brand: 'Basic Wear',
    images: [
      'https://via.placeholder.com/400x400/FF6B6B/ffffff?text=Áo+Thun+1',
      'https://via.placeholder.com/400x400/4ECDC4/ffffff?text=Áo+Thun+2',
      'https://via.placeholder.com/400x400/45B7D1/ffffff?text=Áo+Thun+3',
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Đen', code: '#000000' },
      { name: 'Trắng', code: '#ffffff' },
      { name: 'Xám', code: '#6b7280' },
    ],
    rating: 4.5,
    reviewCount: 128,
    inStock: true,
    sku: 'AT001-BL',
    featured: true,
    createdAt: '2024-01-15',
  },
  {
    id: 2,
    name: 'Áo sơ mi nam trắng công sở',
    slug: 'ao-so-mi-nam-trang-cong-so',
    price: 349000,
    discountPrice: null,
    discount: 0,
    description: 'Áo sơ mi nam màu trắng phù hợp cho công sở, chất liệu vải lụa cao cấp, form dáng chuẩn.',
    categoryId: 2,
    categorySlug: 'ao-so-mi',
    category: 'Áo sơ mi',
    brand: 'Office Style',
    images: [
      'https://via.placeholder.com/400x400/96CEB4/ffffff?text=Áo+Sơ+Mi',
      'https://via.placeholder.com/400x400/FECA57/ffffff?text=Áo+Sơ+Mi',
    ],
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Trắng', code: '#ffffff' },
      { name: 'Xanh nhạt', code: '#93c5fd' },
    ],
    rating: 4.2,
    reviewCount: 89,
    inStock: true,
    sku: 'ASM002-WH',
    featured: true,
    createdAt: '2024-02-10',
  },
  {
    id: 3,
    name: 'Quần jean nam rách gối',
    slug: 'quan-jean-nam-rach-goi',
    price: 499000,
    discountPrice: 399000,
    discount: 20,
    description: 'Quần jean nam phong cách streetwear với thiết kế rách gối thời trang. Chất liệu denim bền đẹp.',
    categoryId: 3,
    categorySlug: 'quan-jean',
    category: 'Quần jean',
    brand: 'Denim Club',
    images: [
      'https://via.placeholder.com/400x400/FF9FF3/ffffff?text=Quần+Jean',
      'https://via.placeholder.com/400x400/F368E0/ffffff?text=Quần+Jean',
    ],
    sizes: ['28', '30', '32', '34', '36'],
    colors: [
      { name: 'Xanh đậm', code: '#1e40af' },
      { name: 'Xanh nhạt', code: '#60a5fa' },
      { name: 'Đen', code: '#000000' },
    ],
    rating: 4.7,
    reviewCount: 204,
    inStock: true,
    sku: 'QJ003-BL',
    featured: true,
    createdAt: '2024-01-28',
  },
  {
    id: 4,
    name: 'Quần short nam thể thao',
    slug: 'quan-short-nam-the-thao',
    price: 229000,
    discountPrice: 179000,
    discount: 22,
    description: 'Quần short nam thể thao thoáng mát, chất liệu thun lạnh co giãn tốt. Phù hợp cho tập luyện và đi chơi.',
    categoryId: 4,
    categorySlug: 'quan-short',
    category: 'Quần short',
    brand: 'Sport Life',
    images: [
      'https://via.placeholder.com/400x400/54A0FF/ffffff?text=Quần+Short',
      'https://via.placeholder.com/400x400/5F27CD/ffffff?text=Quần+Short',
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Đen', code: '#000000' },
      { name: 'Xám', code: '#6b7280' },
      { name: 'Xanh navy', code: '#1e3a8a' },
    ],
    rating: 4.3,
    reviewCount: 67,
    inStock: true,
    sku: 'QS004-BK',
    featured: false,
    createdAt: '2024-03-05',
  },
  {
    id: 5,
    name: 'Đầm maxi hoa nhí nữ tính',
    slug: 'dam-maxi-hoa-nhi-nu-tinh',
    price: 599000,
    discountPrice: 449000,
    discount: 25,
    description: 'Đầm maxi dài thướt tha với họa tiết hoa nhí nữ tính. Chất liệu voan mềm mại, thoáng mát.',
    categoryId: 5,
    categorySlug: 'dam-vay',
    category: 'Đầm/Váy',
    brand: 'Lady Style',
    images: [
      'https://via.placeholder.com/400x400/FF9FF3/ffffff?text=Đầm+Maxi',
      'https://via.placeholder.com/400x400/F368E0/ffffff?text=Đầm+Maxi',
    ],
    sizes: ['S', 'M', 'L'],
    colors: [
      { name: 'Hồng', code: '#f472b6' },
      { name: 'Trắng', code: '#ffffff' },
      { name: 'Vàng', code: '#facc15' },
    ],
    rating: 4.8,
    reviewCount: 156,
    inStock: true,
    sku: 'DM005-PK',
    featured: true,
    createdAt: '2024-02-22',
  },
  {
    id: 6,
    name: 'Áo khoác denim nam',
    slug: 'ao-khoac-denim-nam',
    price: 799000,
    discountPrice: 649000,
    discount: 19,
    description: 'Áo khoác denim nam phong cách casual, chất liệu denim dày dặn, bền đẹp. Có thể mặc nhiều mùa.',
    categoryId: 6,
    categorySlug: 'ao-khoac',
    category: 'Áo khoác',
    brand: 'Denim Club',
    images: [
      'https://via.placeholder.com/400x400/54A0FF/ffffff?text=Áo+Khoác',
      'https://via.placeholder.com/400x400/5F27CD/ffffff?text=Áo+Khoác',
    ],
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Xanh đậm', code: '#1e40af' },
      { name: 'Đen', code: '#000000' },
    ],
    rating: 4.4,
    reviewCount: 92,
    inStock: true,
    sku: 'AK006-BL',
    featured: true,
    createdAt: '2024-01-30',
  },
  {
    id: 7,
    name: 'Áo len cổ lọ nữ',
    slug: 'ao-len-co-lo-nu',
    price: 329000,
    discountPrice: 279000,
    discount: 15,
    description: 'Áo len cổ lọ nữ chất liệu len pha cotton ấm áp, mềm mại. Phù hợp cho mùa đông hoặc điều hòa.',
    categoryId: 7,
    categorySlug: 'ao-len',
    category: 'Áo len',
    brand: 'Winter Collection',
    images: [
      'https://via.placeholder.com/400x400/FF6B6B/ffffff?text=Áo+Len',
      'https://via.placeholder.com/400x400/4ECDC4/ffffff?text=Áo+Len',
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [
      { name: 'Đỏ', code: '#dc2626' },
      { name: 'Trắng', code: '#ffffff' },
      { name: 'Xám', code: '#6b7280' },
      { name: 'Hồng', code: '#f472b6' },
    ],
    rating: 4.6,
    reviewCount: 113,
    inStock: true,
    sku: 'AL007-RD',
    featured: false,
    createdAt: '2023-12-15',
  },
  {
    id: 8,
    name: 'Mũ lưỡi trai unisex',
    slug: 'mu-luoi-trai-unisex',
    price: 99000,
    discountPrice: null,
    discount: 0,
    description: 'Mũ lưỡi trai unisex thời trang, chất liệu vải bền đẹp, có thể điều chỉnh size. Phụ kiện không thể thiếu.',
    categoryId: 8,
    categorySlug: 'phu-kien',
    category: 'Phụ kiện',
    brand: 'Accessory Zone',
    images: [
      'https://via.placeholder.com/400x400/96CEB4/ffffff?text=Mũ+Lưỡi+Trai',
      'https://via.placeholder.com/400x400/FECA57/ffffff?text=Mũ+Lưỡi+Trai',
    ],
    sizes: ['Free Size'],
    colors: [
      { name: 'Đen', code: '#000000' },
      { name: 'Trắng', code: '#ffffff' },
      { name: 'Xanh navy', code: '#1e3a8a' },
      { name: 'Đỏ', code: '#dc2626' },
      { name: 'Cam', code: '#ea580c' },
    ],
    rating: 4.1,
    reviewCount: 45,
    inStock: true,
    sku: 'ML008-BK',
    featured: false,
    createdAt: '2024-03-10',
  },
  {
    id: 9,
    name: 'Áo thun nữ crop top',
    slug: 'ao-thun-nu-crop-top',
    price: 179000,
    discountPrice: 129000,
    discount: 28,
    description: 'Áo thun nữ crop top trẻ trung, năng động. Chất liệu cotton mềm mại, thoáng mát.',
    categoryId: 1,
    categorySlug: 'ao-thun',
    category: 'Áo thun',
    brand: 'Young Style',
    images: [
      'https://via.placeholder.com/400x400/FF9FF3/ffffff?text=Crop+Top',
      'https://via.placeholder.com/400x400/F368E0/ffffff?text=Crop+Top',
    ],
    sizes: ['XS', 'S', 'M'],
    colors: [
      { name: 'Trắng', code: '#ffffff' },
      { name: 'Hồng', code: '#f472b6' },
      { name: 'Vàng', code: '#facc15' },
      { name: 'Xanh mint', code: '#99f6e4' },
    ],
    rating: 4.5,
    reviewCount: 87,
    inStock: true,
    sku: 'AT009-WH',
    featured: true,
    createdAt: '2024-02-28',
  },
  {
    id: 10,
    name: 'Quần jean nữ ống loe',
    slug: 'quan-jean-nu-ong-loe',
    price: 549000,
    discountPrice: 439000,
    discount: 20,
    description: 'Quần jean nữ ống loe phong cách vintage, chất liệu denim mềm, co giãn tốt. Tôn dáng người mặc.',
    categoryId: 3,
    categorySlug: 'quan-jean',
    category: 'Quần jean',
    brand: 'Vintage Denim',
    images: [
      'https://via.placeholder.com/400x400/54A0FF/ffffff?text=Quần+Loe',
      'https://via.placeholder.com/400x400/5F27CD/ffffff?text=Quần+Loe',
    ],
    sizes: ['26', '28', '30', '32'],
    colors: [
      { name: 'Xanh nhạt', code: '#60a5fa' },
      { name: 'Xanh đậm', code: '#1e40af' },
    ],
    rating: 4.7,
    reviewCount: 134,
    inStock: true,
    sku: 'QJ010-LB',
    featured: true,
    createdAt: '2024-02-15',
  },
  {
    id: 11,
    name: 'Áo sơ mi nữ hoa nhí',
    slug: 'ao-so-mi-nu-hoa-nhi',
    price: 389000,
    discountPrice: 299000,
    discount: 23,
    description: 'Áo sơ mi nữ họa tiết hoa nhí thanh lịch, chất liệu lụa mềm mại, form dáng ôm nhẹ.',
    categoryId: 2,
    categorySlug: 'ao-so-mi',
    category: 'Áo sơ mi',
    brand: 'Flower Pattern',
    images: [
      'https://via.placeholder.com/400x400/FF6B6B/ffffff?text=Áo+Hoa',
      'https://via.placeholder.com/400x400/4ECDC4/ffffff?text=Áo+Hoa',
    ],
    sizes: ['S', 'M', 'L'],
    colors: [
      { name: 'Trắng', code: '#ffffff' },
      { name: 'Hồng nhạt', code: '#fbcfe8' },
      { name: 'Xanh pastel', code: '#bfdbfe' },
    ],
    rating: 4.4,
    reviewCount: 76,
    inStock: true,
    sku: 'ASM011-WH',
    featured: false,
    createdAt: '2024-03-01',
  },
  {
    id: 12,
    name: 'Áo khoác bomber nam',
    slug: 'ao-khoac-bomber-nam',
    price: 699000,
    discountPrice: 559000,
    discount: 20,
    description: 'Áo khoác bomber nam phong cách streetwear, chất liệu nylon chống thấm nước nhẹ. Có túi zip tiện lợi.',
    categoryId: 6,
    categorySlug: 'ao-khoac',
    category: 'Áo khoác',
    brand: 'Street Style',
    images: [
      'https://via.placeholder.com/400x400/96CEB4/ffffff?text=Bomber',
      'https://via.placeholder.com/400x400/FECA57/ffffff?text=Bomber',
    ],
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Đen', code: '#000000' },
      { name: 'Xanh đen', code: '#1e293b' },
      { name: 'Xanh army', code: '#365314' },
    ],
    rating: 4.6,
    reviewCount: 102,
    inStock: true,
    sku: 'AK012-BK',
    featured: true,
    createdAt: '2024-02-05',
  },
];

// Get featured products
export const getFeaturedProducts = () => {
  return mockProducts.filter(product => product.featured);
};

// Get new arrivals
export const getNewArrivals = () => {
  return [...mockProducts]
    .sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt))
    .slice(0, 8);
};

// Get products by category
export const getProductsByCategory = (categorySlug) => {
  return mockProducts.filter(product => product.categorySlug === categorySlug);
};